#!/bin/bash
# run this as root on a first install to get most of your environmnet up
# then run the environment setup
# remove the comments for the other groups you wish to install
#Installed Environment Groups:
dnf install
'Fedora Server Edition'
'LXDE Desktop'
'Cinnamon Desktop'
#Installed Groups:
'Administration Tools'
'Authoring and Publishing'
'Books and Guides'
'C Development Tools and Libraries'
'Cloud Management Tools'
'Container Management'
'Development Tools'
'Editors'
'Games and Entertainment'
'Headless Management'
'LibreOffice'
'MATE Applications'
'Network Servers'
'Office/Productivity'
'Python Classroom'
'Security Lab'
'System Tools'
'Text-based Internet'
#Available Environment Groups:
#'Fedora Custom Operating System'
#'Minimal Install'
#'Fedora Workstation'
#'Fedora Cloud Server'
#'KDE Plasma Workspaces'
#'Xfce Desktop'
#'LXQt Desktop'
#'MATE Desktop'
#'Sugar Desktop Environment'
#'Deepin Desktop'
#'Development and Creative Workstation'
#'Web Server'
#'Infrastructure Server'
#'Basic Desktop'
#Available Groups:
#'3D Printing'
#'Audio Production'
#'Cloud Infrastructure'
#'Compiz'
#'D Development Tools and Libraries'
#'Design Suite'
#'Domain Membership'
#'Fedora Eclipse'
#'Educational Software'
#'Electronic Lab'
#'Engineering and Scientific'
#'FreeIPA Server'
#'Medical Applications'
#'Milkymist'
#'Neuron Modelling Simulators'
#'Python Science'
"dnf-setup-groups.sh" 61L, 1285C                                                                                                                                                                                            3,12          Top
